Json logging
davilimap/slow-cheetah pull request #8
Opened 2017-04-04 00:19 UTC by davilimap

Adding logging capabilities for JSON transformations

2017-04-04 18:19 UTC, jviau requested changes
1. You added the `logger` parameter everywhere - add argument validation for it on all non-private methods.
2. Look over the new types added and add `readonly` and remove `set` (or switch to `private set`) where possible.

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JdtException.cs
> +    internal enum ErrorLocation
I don't think `internal` is necessary here. Could be `public`. Along with all the non-newtonsoft contructors and methods in `JdtException`

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformation.cs
> +        private JsonTransformationContextLogger logger;
Can this, or any other fields, be `readonly`?

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformation.cs
> +        public bool Apply(string sourceFile, out Stream result)
Rename to `TryApply` (and rename the one below also) and add back the previous `Apply` methods where it throws exceptions if it fails.

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformation.cs
>              Stream sourceStream = File.Open(sourceFile, FileMode.Open);
This needs to be in a `using`, you are not disposing the stream.

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformation.cs
> +                    if (!this.logger.LogErrorFromException(ex))
The `TryApply` version should not throw for a failed transform. It should only fail for things like file load failure.

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformationContextLogger.cs
> +        private IJsonTransformationLogger externalLogger = null;
`readonly`

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformationContextLogger.cs
> +        internal string SourceFile { get; set; } = "Source";
Any reason for the `set`? It is not used. Same with `TransformFile`.

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformationContextLogger.cs
> +        internal bool HasLoggedErrors { get; set; }
`private set`

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformationContextLogger.cs
> +                    return null;
What happens if this does end up returning `null`? Looking at your uses of it, you pass the result directly into `externalLogger`. What if it throws for `null`?

2017-04-04 18:19 UTC, jviau commented on SlowCheetah.JDT/JsonTransformationContextLogger.cs
> +                return false;
As discussed in person, rethrow the exception here using `ExceptionDispathInfo.Capture(exception).Throw();` Then switch to a `void` return.

2017-04-04 22:05 UTC, davilimap commented on SlowCheetah.JDT/JsonTransformationContextLogger.cs
> +                    return null;
I think the `IJsonTransformationLogger` should be able to handle null values for the file path. It's in the XML doc for the interface.

2017-04-04 22:33 UTC, davilimap commented
@jviau Addressed all of your changes and made a few more changes

2017-04-06 00:53 UTC, jviau requested changes

2017-04-06 00:53 UTC, jviau commented on SlowCheetah.JDT/JsonTransformation.cs
> +        public bool TryApply(string sourceFile, out Stream result)
We need to rethink this API. I didn't realize in my previous comment the logger was part of the constructor. `TryApply` will currently throw when the user has no logger supplied, which is not what a `Try` function should do. I think we need an `Apply` overload that propagates the exception regardless of logger being provided. Then the `TryApply` never throws logger or not.

2017-04-06 00:57 UTC, jviau commented on SlowCheetah.JDT/JsonTransformation.cs
> +        public bool TryApply(string sourceFile, out Stream result)
Other than this issue it looks good.

2017-04-11 01:53 UTC, davilimap commented
@jviau Performed changes in the entry points as discussed.

2017-04-11 19:50 UTC, jviau commented
Sorry to go back and forth on the design of TryApply vs Apply, but as discussed in person lets remove the TryApply for now. It hides too much information of why it failed to the caller. We can revisit a TryApply method in the future if the demand is there.

2017-04-11 21:54 UTC, jviau approved these changes

2017-04-11 21:59 UTC, merged